-- announcer_config.lua (remote file)
return {
  version = "1.0.0",
  baseUrl = "https://github.com/localscripts/Audio/raw/refs/heads/main/QuakeANNC/",
  folder  = "QuakeSounds",

  Sounds = {
    assassin="assassin.wav", bullseye="bullseye.wav", comboking="comboking.wav",
    dominating="dominating.wav", dominating2="dominating2.wav",
    doublekill="doublekill.wav", doublekill2="doublekill2.wav", doublekill3="doublekill3.wav",
    eagleeye="eagleeye.wav", eagleeye2="eagleeye2.wav",
    excellent="excellent.wav",
    firstblood="firstblood.wav", firstblood2="firstblood2.wav", firstblood3="firstblood3.wav", firstblood4="firstblood4.wav",
    flawlessvictory="flawlessvictory.wav",
    godlike="godlike.wav", godlike2="godlike2.wav",
    hattrick="hattrick.wav", hattrick2="hattrick2.wav",
    headhunter="headhunter.wav", headhunter2="headhunter2.wav",
    headshot="headshot.wav", headshot2="headshot2.wav", headshot3="headshot3.wav", headshot4="headshot4.wav",
    hexakill="hexakill.wav",
    holyshit="holyshit.wav",
    humiliating="humiliating.wav", humiliatingdefeat="humiliatingdefeat.wav", humiliation="humiliation.wav",
    iamtheoneandonly="iamtheoneandonly.wav",
    impressive="impressive.wav",
    killingmachine="killingmachine.wav",
    killingspree="killingspree.wav", killingspree2="killingspree2.wav",
    laughs="laughs.wav", laughs2="laughs2.wav", laughs3="laughs3.wav", laughs4="laughs4.wav",
    ludicrouskill="ludicrouskill.wav",
    maniac="maniac.wav",
    massacre="massacre.wav",
    megakill="megakill.wav", megakill2="megakill2.wav",
    monsterkill="monsterkill.wav", monsterkill2="monsterkill2.wav",
    multikill="multikill.wav", multikill2="multikill2.wav",
    outstanding="outstanding.wav",
    ownage="ownage.wav",
    pancake="pancake.wav",
    payback="payback.wav",
    pentakill="pentakill.wav",
    pickupyourweaponsandfight="pickupyourweaponsandfight.wav",
    play="play.wav",
    prepareforbattle="prepareforbattle.wav", preparetofight="preparetofight.wav",
    quadrakill="quadrakill.wav",
    rampage="rampage.wav", rampage2="rampage2.wav",
    retribution="retribution.wav",
    shutdown="shutdown.wav",
    teamkiller="teamkiller.wav",
    triplekill="triplekill.wav",
    ultrakill="ultrakill.wav", ultrakill2="ultrakill2.wav",
    unreal="unreal.wav",
    unstoppable="unstoppable.wav", unstoppable2="unstoppable2.wav",
    vengeance="vengeance.wav",
    whickedsick="whickedsick.wav",
    youarethelastmanstanding="youarethelastmanstanding.wav",
    yourefunny="yourefunny.wav",
  },

  FragMap = {
    [3]="triplekill",[5]="multikill",[6]="rampage",[7]="killingspree",[8]="dominating",
    [9]="impressive",[10]="unstoppable",[11]="outstanding",[12]="megakill",[13]="ultrakill",
    [14]="eagleeye",[15]="ownage",[16]="comboking",[17]="maniac",[18]="ludicrouskill",
    [19]="bullseye",[20]="excellent",[21]="pancake",[22]="headhunter",[23]="unreal",
    [24]="assassin",[25]="whickedsick",[26]="massacre",[27]="killingmachine",
    [28]="monsterkill",[29]="holyshit",[30]="godlike",
  },

  SpecialMap = {
    HeadShot={"headshot","headshot2","headshot3","headshot4"},
    Suicide={"yourefunny"},
    GrenadeKill={"laughs","shutdown"},
    TeamKill={"teamkiller"},
    KnifeKill={"humiliatingdefeat","humiliation","humiliating"},
    FirstBlood={"firstblood","firstblood2","firstblood3","firstblood4"},
    RoundStart={"pickupyourweaponsandfight","play","preparetofight","prepareforbattle"},
    DoubleKill={"doublekill","doublekill2","doublekill3"},
    Hattrick={"hattrick","hattrick2"},
    LastManStanding={"youarethelastmanstanding","iamtheoneandonly"},
    FlawlessVictory={"flawlessvictory"},
    Revenge={"payback","vengeance","retribution"},
  }
}
